train_datasets:
  - dataset_name: xeno-canto
    dataset_version: 0.1
    split: train
    balance: false
    balance_attribute: canonical_name   # balance data across via this attribute
    custom_balancing: false
    balancing_method: upsample
    subset_percentage: 1.0              # <1 to consider a subset of data
    audio_max_length_seconds: 5
    audio_path_col: path
    sample_rate: 32000
    # data_root: ../esp-data/xeno_canto_32khz
    # data_root: /scratch-representation-learning/
    transformations:
      - type: labels_from_features
        features: [canonical_name]
        output_feature: label
        override: true


val_datasets:
  - dataset_name: xeno-canto
    dataset_version: 0.1
    split: validation
    balance: false
    balance_attribute: canonical_name   # balance data across via this attribute
    custom_balancing: false
    balancing_method: upsample
    subset_percentage: 1.0              # <1 to consider a subset of data
    audio_max_length_seconds: 5
    audio_path_col: path
    sample_rate: 32000
    transformations:
      - type: labels_from_features
        features: [canonical_name]
        output_feature: label
        override: true
    # data_root: gs://foundation-model-data/audio_16k/
    # data_root: ../esp-data/xeno_canto_32khz
    # data_root: /scratch-representation-learning/

# transformations:
#   - type: deduplicate
#     subset: ['relative_path']
