---
# EAT model fine-tuned on AnimalSpeak dataset with SSL
# Default checkpoint path for this model (can be overridden when loading)
checkpoint_path: gs://representation-learning/models/sl_eat_animalspeak_ssl_all.pt
# Temporary class mapping path, in the future this should be read from
# the checkpoint directory
class_mapping_path: gs://representation-learning/runs/aaai/sl_beats_animalspeak_audioset/2025-08-11_09-30-49/label_map.json

model_spec:
  name: eat_hf
  pretrained: false  # Set to false when loading from checkpoint
  device: cuda
  # Combined dataset - using default normalization parameters
  eat_norm_mean: -5.553
  eat_norm_std: 4.606
  audio_config:
    sample_rate: 16000
    representation: raw
    normalize: false
    target_length_seconds: 10
    window_selection: random
