---
# EfficientNet model fine-tuned on AnimalSpeak dataset
# Default checkpoint path for this model (can be overridden when loading)
checkpoint_path: gs://representation-learning/models/efficientnet_animalspeak.pt
# Temporary class mapping path, in the future this should be read from
# the checkpoint directory
class_mapping_path: gs://representation-learning/runs/aaai/sl_beats_animalspeak_real/2025-07-20_09-18-31/label_map.json

model_spec:
  name: efficientnet
  pretrained: false  # Set to false when loading from checkpoint
  device: cuda
  audio_config:
    sample_rate: 16000
    n_fft: 800
    hop_length: 160
    win_length: 800
    window: hann
    n_mels: 128
    representation: mel_spectrogram
    normalize: true
    target_length_seconds: 10
    window_selection: random
