benchmark_name: "bioacoustic_benchmark"

evaluation_sets:
  # Detection Tasks
  - name: "hiceas_detection"
    train: &hiceas_base
      dataset_name: beans
      split: hiceas_train
      type: detection
      label_column: labels_as_list
      audio_path_col: path
      multi_label: true
      label_type: supervised
      audio_max_length_seconds: 5
      transformations:
        # Convert list labels to multi-label format
        - type: labels_from_features
          features:
            - labels_as_list
          override: true
          label_map: {"Minke whale": 0}
      # sample_rate: 16000
    validation:
      <<: *hiceas_base
      split: hiceas_validation
    test:
      <<: *hiceas_base
      split: hiceas_test
    metrics: [mAP]

  - name: "hainan_gibbons_detection"
    train: &gibbons_base
      dataset_name: beans
      split: hainan_gibbons_train
      type: detection
      label_column: labels_as_list
      audio_path_col: path
      multi_label: true
      label_type: supervised
      audio_max_length_seconds: 5
      transformations:
        # Convert list labels to multi-label format
        - type: labels_from_features
          features:
            - labels_as_list
          override: true
          label_map: {'Gibbon duet': 0, 'Multiple pulse gibbon call': 1, 'Single pulse gibbon call': 2}
      # sample_rate: 16000
    validation:
      <<: *gibbons_base
      split: hainan_gibbons_validation
    test:
      <<: *gibbons_base
      split: hainan_gibbons_test
    metrics: [mAP]

  - name: "dcase_detection"
    train: &dcase_base
      dataset_name: beans
      split: dcase_train
      type: detection
      label_column: labels_as_list
      audio_path_col: path
      multi_label: true
      label_type: supervised
      audio_max_length_seconds: 5
      transformations:
        - type: labels_from_features
          features:
            - labels_as_list
          override: true
          label_map: {'American Redstart': 0, 'Bay-breasted Warbler': 1, 'Black-throated Blue Warbler': 2, 'Chipping Sparrow': 3, 'Common Yellowthroat': 4, 'Gray-cheeked Thrush': 5, 'Hyena giggle': 6, 'Hyena groan and moo': 7, 'Hyena squitter': 8, 'Jackdaw call': 9, 'Meerkat close call': 10, 'Meerkat short note': 11, 'Other Animal': 12, 'Ovenbird': 13, 'Rose-breasted Grosbeak': 14, 'Savannah Sparrow': 15, "Swainson's Thrush": 16, 'White-throated Sparrow': 17}
      # sample_rate: 16000
    validation:
      <<: *dcase_base
      split: dcase_validation
    test:
      <<: *dcase_base
      split: dcase_test
    metrics: [mAP]

  - name: "enabirds_detection"
    train: &enabirds_base
      dataset_name: beans
      split: enabirds_train
      type: detection
      label_column: labels_as_list
      audio_path_col: path
      multi_label: true
      label_type: supervised
      audio_max_length_seconds: 5
      transformations:
        - type: labels_from_features
          features:
            - labels_as_list
          override: true
          label_map: {'American Crow': 0, 'American Goldfinch': 1, 'American Redstart': 2, 'American Robin': 3, 'Black-and-white Warbler': 4, 'Black-capped Chickadee': 5, 'Black-throated Blue Warbler': 6, 'Black-throated Green Warbler': 7, 'Blue Jay': 8, 'Blue-gray Gnatcatcher': 9, 'Blue-headed Vireo': 10, 'Brown-headed Cowbird': 11, 'Carolina Wren': 12, 'Common Yellowthroat': 13, 'Eastern Towhee': 14, 'Hermit Thrush': 15, 'Hooded Warbler': 16, "Kirtland's Warbler": 17, 'Louisiana Waterthrush': 18, 'None': 19, 'Northern Cardinal': 20, 'Northern Flicker': 21, 'Other Bird': 22, 'Ovenbird': 23, 'Red-bellied Woodpecker': 24, 'Red-eyed Vireo': 25, 'Rose-breasted Grosbeak': 26, 'Ruby-crowned Kinglet': 27, 'Scarlet Tanager': 28, "Swainson's Thrush": 29, 'Tufted Titmouse': 30, 'White-breasted Nuthatch': 31, 'Wild Turkey': 32, 'Wood Thrush': 33, 'Yellow-billed Cuckoo': 34}
      # sample_rate: 16000

    validation:
      <<: *enabirds_base
      split: enabirds_validation
    test:
      <<: *enabirds_base
      split: enabirds_test
    metrics: [mAP]

  - name: "rfcx_detection"
    train: &rfcx_base
      dataset_name: beans
      split: rfcx_train
      type: detection
      label_column: labels_as_list
      audio_path_col: path
      multi_label: true
      label_type: supervised
      audio_max_length_seconds: 5
      transformations:
        # Convert list labels to multi-label format
        - type: labels_from_features
          features:
            - labels_as_list
          override: true
          label_map: {'Bananaquit': 0, 'Black-whiskered vireo': 1, 'Bronze coqui': 2, 'Common coqui': 3, 'Cricket coqui': 4, 'Dwarf coqui': 5, 'Elfin woods warbler': 6, 'Grass coqui': 7, "Hedrick's coqui": 8, 'Locust coqui': 9, 'Melodius coqui': 10, 'Mountain Coqui': 11, 'Pearly-eyed thrasher': 12, 'Puerto Rican bullfinch': 13, 'Puerto Rican lizard cuckoo': 14, 'Puerto Rican owl': 15, 'Puerto Rican spindalis': 16, 'Puerto Rican tanager': 17, 'Puerto Rican tody': 18, 'Puerto Rican woodpecker': 19, 'Red-eyed coqui': 20, 'Red-legged thrush': 21, 'Scaly-naped pigeon': 22, 'White-lipped Frog': 23}
      # sample_rate: 16000
    validation:
      <<: *rfcx_base
      split: rfcx_validation
    test:
      <<: *rfcx_base
      split: rfcx_test
    metrics: [mAP]
