data_path: benchmark
datasets:
  - dataset_name: watkins
    type: classification
    label_column: label
    audio_path_col: path
    multi_label: false
    label_type: supervised
    audio_max_length_seconds: 3
    transformations:
      - type: label_from_feature
        feature: label
        override: true
    # transformations:
    #   - type: uniform_sample
    #     property: label
    #     ratio: 0.01
    sample_rate: 16000
    metrics:
      - accuracy
      - balanced_accuracy
