data_path: benchmark

datasets:
  - dataset_name: bats
    type: classification
    label_column: label
    audio_path_col: path
    multi_label: false
    label_type: supervised
    audio_max_length_seconds: 5
    # transformations:
    #   - type: uniform_sample
    #     property: label
    #     ratio: 0.01
    metrics:
      - accuracy
      - balanced_accuracy
