---
# Selects a raw dataset (AnimalSpeak)
<<<<<<< HEAD
data_config_name: bio_base
dataset_name: animalspeak
=======
dataset_name: bio_base
source_dataset_name: animalspeak
train_path: gs://animalspeak2/splits/v1/animalspeak_train_v1.3.csv
valid_path: gs://animalspeak2/splits/v1/animalspeak_eval_v1.3.csv
>>>>>>> 3b963cb13a581c50f8b0a93a7adbaae8c8af087c
dataset_version: 0.0
balance: false
balance_attribute: canonical_name   # balance data across via this attribute
custom_balancing: false
balancing_method: upsample
<<<<<<< HEAD
<<<<<<< HEAD
subset_percentage: 1.0              # <1 to consider a subset of data
=======
=======
>>>>>>> 3b963cb13a581c50f8b0a93a7adbaae8c8af087c
transformations: None
>>>>>>> 3b963cb (uniform sampling as a data transformation)
label_column: canonical_name
audio_max_length_seconds: 10
label_type: supervised
transformations: []
