dataset_name: animalspeak
split: train
output_take_and_give:
  audio: raw_wav
  text_label: label
  label: label
data_root: /home/milad_earthspecies_org/data-migration/marius-highmem/mnt/foundation-model-data/audio/

transformations:
  - type: label_from_feature
    feature: canonical_name
    output_feature: label
