# Selects a raw dataset (AnimalSpeak)
dataset_name: bio_base
source_dataset_name: animalspeak
train_path: gs://animalspeak2/splits/v1/animalspeak_train_v1.3.csv
valid_path: gs://animalspeak2/splits/v1/animalspeak_eval_v1.3.csv
dataset_version: 0.0
dataset_source: ./animalspeak.csv   # REMOVE
balance: false
balance_attribute: canonical_name   # balance data across via this attribute
custom_balancing: false
balancing_method: upsample
transformations: None
label_column: canonical_name
label_type: supervised