dataset_name: animalspeak
dataset_version: 0.0
balance: false
balance_attribute: canonical_name   # balance data across via this attribute
custom_balancing: false
balancing_method: upsample
subset_percentage: 1.0              # <1 to consider a subset of data
audio_max_length_seconds: 10

transformations:
  - type: label_from_feature
    feature: canonical_name

  # Only keep recordings from the specified sources
  - type: filter
    mode: include
    property: source
    values: [xeno-canto, iNaturalist, Watkins]

  # Sub-sample each class at different rates
  - type: subsample
    property: class
    ratios:
      birds: 0.20
      mammals: 0.50
      amphibians: 0.70
      reptiles: 1.00
      fish: 1.00
      insects: 1.00
      other: 1.00
