data_config_name: bio_base
dataset_name: animalspeak
dataset_version: 0.0
balance: false
balance_attribute: canonical_name   # balance data across via this attribute
custom_balancing: false
balancing_method: upsample
label_column: canonical_name
label_type: supervised
audio_max_length_seconds: 10
multi_label: false

transformations:
  # 1. Keep only recordings from the specified sources
  - property: source
    values: [xeno-canto, iNaturalist, Watkins]
    operation: include

  # 2. Subâ€‘sample each class at different rates
  - property: class
    operation: subsample
    ratios:
      birds:       0.20
      mammals:     0.50
      amphibians:  0.70
      reptiles:    1.00
      fish:        1.00
      insects:     1.00
      other:       1.00
