data_path: benchmark

datasets:
  - dataset_name: voxaboxen-dummy
    type: detection
    label_column: answer
    audio_path_col: path
    multi_label: true
    label_type: supervised
    audio_max_length_seconds: 5
    strong_detection: true
    transformations:
      - type: labels_from_features
        features:
          - answer
        override: true
        label_map: {'Bird': 0, 'Marine Mammal': 1, 'None': 2, 'Terrestrial Mammal': 3}
    sample_rate: 16000
    metrics:
      - f1_strong
